@startuml Silence Radio
package "controleurs" {
    class ApplicationRadio {
    	- scene : Scene
    	- stage : Stage
    	- vueEmetteur : ControleurVueEmetteur
    	- vueRecepteur : ControleurVueRecepteur
    	- vueMenu : ControleurVueMenu
        + void start(Stage stagePrincipal)
        + {static} void main()
        - void showVueMenu(Stage stage)
        + void showVueEmetteur()
        + void showVueRecepteur()
        + Stage getStage()
        + Stage getScene()
        - void setOptionRetour()
    }
    
    class ControleurEnvoi {
        - {static} void envoyer(Byte[] bytes)
    }
    
    note top of ControleurReception : Le corps de cette classe reste à déterminer
    class ControleurReception{
        + void ControleurReception()
    }
}

package "vue" {
    class ControleurVueEmetteur {
    	- borderPaneRoot : BorderPane
    	- btnSelectionner : Button
    	- btnEnvoyer : Button
    	- slider : Slider
    	- freqLabel : Label
    	- sliderLabel : Label
    	- labelProgress : Label
    	- vboxMessages : VBox
    	- paneAnimation : Pane
        - application : ApplicationRadio = null
        + {static} final ADRESSE_VUE_EMETTEUR : String = "/vues/Vue_Emetteur.fxml"
        - final fileChooser : FileChooser = new FileChooser()
        - file : File
        - nbrMessage : int = 0
        - anim : AnimationSinus = new AnimationSinus()
        + void setApplication(ApplicationRadio application)
        + BorderPane getBorderPaneRoot()
        - void clickedBtnEnvoyer(ActionEvent event)
        - void clickedBtnSelect(ActionEvent event)
        + void bindSlider()
        - void afficherAnimation()
        - void arretAnimation()
        + String getEmplacementFichierSelect()
    }

    class ControleurVueRecepteur {
        - borderPaneRoot : BorderPane
    	- btnSelectionner : Button
    	- btnEnregistrer : Button
    	- slider : Slider
    	- freqLabel : Label
    	- sliderLabel : Label
    	- labelProgress : Label
    	- vboxMessages : VBox
        - application : ApplicationRadio = null
        + {static} final ADRESSE_VUE_RECEPTEUR : String = "/vues/Vue_Recepteur.fxml"
        - final directoryChooser : DirectoryChooser = new DirectoryChooser()
        - file : File
        - nbrMessage : int = 0
        + void setApplication(ApplicationRadio application)
        + BorderPane getBorderPaneRoot()
        - void clickedBtnEnregistrer(ActionEvent event)
        - void clickedBtnSelect(ActionEvent event)
        + void bindSlider()
        + String getEmplacementFichierSelect()
    }

    class ControleurVueMenu {
    	- darkNGreen RadioMenuItem
    	- blueNRed RadioMenuItem
        - vboxRoot : VBox
        - btnEmettre : Button
        - btnReception : Button
        - themeCourant : String = DARK_N_GREEN
        + {static} final DARK_N_GREEN : String = "/styles/DarkNGreen.css"
        + {static} final BLUE_N_RED : String = "/styles/BlueNRed.css"
        - application : ApplicationRadio = null
        + {static} final ADRESSE_VUE_MENU : String = "/vues/Vue_Menu.fxml"
        + void setApplication(ApplicationRadio application)
        + VBox getVboxRoot()
        - void clickedBtnEmettre(ActionEvent event)
        - void clickedBtnReception(ActionEvent event)
        - void selectedDarkNGreen(ActionEvent event)
        - void selectedBlueNRed(ActionEvent event)
        + String getThemeCourant()
    }
}

package "modeles.emetteur" {
    class RepresentationBinaire {
        - octets : OctetBinaire[]
        - octetCourant : int
        + RepresentationBinaire(byte[] bytes)
        + OctetBinaire[] getOctets()
        + boolean hasNext()
        + OctetBinaire next()
        + Iterator<OctetBinaire> iterator()
        - {static} boolean validerOctets(byte[] octets)
    }

    class OctetBinaire {
        - bits : byte[]
        + OctetBinaire(byte b)
        - void calculerBits(byte b)
        + byte[] getBits()
        - {static} boolean validerByte(byte b)
        + String toString()
        + boolean equals(Object obj)
    }

    class GenerateurSon {
        + octets : List<OctetBinaire>
        + notes : List<Note>
        + void GenerateurSon(List<OctetBinaire> octets)
        - Note genererNote(byte b)
        - void genererNotes()
    }

    class Note {
        - numeroNote : int
        - velocite : int
        + void Note(int numeroNote, int velocite)
    }

    class LecteurSon {
        + void LecteurSon(List<Note>)
        + void jouerSon(Note note)
        + void jouerSons()
    }
}

package "modeles.receveur" {
    class EcouteurSignaux{
        - enEcoute : boolean
        + void EcouteurSignaux()
        + void ecouter()
        + void arreterEcouter()
    }

    class Signal{
        - valeur : ValeurSignal
        + void Signal(ValeurSignal signal)
        + byte obtenirValeurBit()
    }

    enum ValeurSignal{
        HAUT
        BAS
    }
}

package "passerelle" {
    class PasserelleFichier{
        + {static} byte[] lireOctets(File fichier)
        + {static} void ecrireOctets(byte[] octets)
        + {static} void ecrireOctets(RepresentationBinaire binaire)
        + {static} File obtenirFichier(String chemin)
    }
}

package "tests" {
    class TestOctetBinaire {
        ob : OctetBinaire
        + void testOctetBinaire()
        + void testOctetBinaireInvalide()
        + void testCalculerBits()
        + void testEquals()
        + void testToString()
    }

    class TestPasserelleFichier {
        + void testLireFichier()
    }

    class TestRepresentationBinaire {
        rb : RepresentationBinaire
        octets : byte[] = {0, 1, 2, 3};
        + void testRepresentationBinaire()
        + void testRepresentationBinaireInvalide()
        + void testGetOctets()
        + void testIterator()
    }

    class TestSuite {
    }
}

interface Iterable<OctetBinaire> {
    + OctetBinaire next()
    + boolean hasNext()
}
interface Iterator<OctetBinaire> {
    + Iterator<OctetBinaire> iterator()
}

ApplicationRadio --> ControleurEnvoi
ControleurEnvoi --> PasserelleFichier
ControleurEnvoi --> RepresentationBinaire
ControleurEnvoi --> GenerateurSon
ControleurEnvoi --> LecteurSon

LecteurSon --> Note

GenerateurSon --> Note
GenerateurSon --> OctetBinaire

RepresentationBinaire --> OctetBinaire
RepresentationBinaire --|> Iterable
RepresentationBinaire --|> Iterator

ControleurReception --> PasserelleFichier
ControleurReception --> EcouteurSignaux

EcouteurSignaux --> OctetBinaire
EcouteurSignaux --> Signal

Signal --> ValeurSignal

TestOctetBinaire --> OctetBinaire
TestPasserelleFichier --> PasserelleFichier
TestRepresentationBinaire --> RepresentationBinaire
@enduml