@startuml Silence Radio
package "controleurs" {
    class ApplicationRadio {
    	- scene : Scene
    	- stage : Stage
    	- vueEmetteur : ControleurVueEmetteur
    	- vueRecepteur : ControleurVueRecepteur
    	- vueMenu : ControleurVueMenu
    	- redimensionnable : boolean = true
        + void start(Stage stagePrincipal)
        + {static} void main()
        - void showVueMenu(Stage stage)
        + void showVueEmetteur()
        + void showVueRecepteur()
        - void demarrageStage(String titre, boolean redimension, Scene scene)
        + Stage getStage()
        + Stage getScene()
        - void setOptionRetour()
    }
    
    class ControleurEnvoi {
        - {static} void envoyer(Byte[] bytes)
    }
    
    note top of ControleurReception : Le corps de cette classe reste à déterminer
    class ControleurReception{
        + void ControleurReception()
    }
}

package "vue" {
    class ControleurVueEmetteur {
    	- borderPaneRoot : BorderPane
    	- btnSelectionner : Button
    	- btnEnvoyer : Button
    	- btnAnnuler : Button
    	- slider : Slider
    	- sliderLabel : Label
    	- labelProgress : Label
    	- labelVitesseFichier : Label
    	- labelTempsEstim : Label
    	- vboxMessages : VBox
    	- paneAnimation : Pane
    	- progressBar : ProgressBar
        - application : ApplicationRadio = null
        + {static} final ADRESSE_VUE_EMETTEUR : String = "/vues/Vue_Emetteur.fxml"
        - final fileChooser : FileChooser = new FileChooser()
        - file : File
        - nbrMessage : int = 0
        - generateurSon : GenerateurSon
        - lecteurSon : LecteurSon
        - dureeSonBit : FloatProperty = new SimpleFloatProperty(0.0001f)
        - threadSon : Thread
        - animProgressBar : AnimationProgressBar
        + void setApplication(ApplicationRadio application)
        + BorderPane getBorderPaneRoot()
        - void clickedBtnEnvoyer(ActionEvent event)
        - void clickedBtnSelect(ActionEvent event)
        + void bindSliderEtLabel()
        - void clickedBtnAnnuler(ActionEvent event)
        + String getEmplacementFichierSelect()
        - void afficherErreur(String emplacement, String detail, Exception ex)
    }

    class ControleurVueRecepteur {
        - borderPaneRoot : BorderPane
    	- btnSelectionner : Button
    	- btnEnregistrer : Button
    	- labelProgress : Label
    	- vboxMessages : VBox
        - application : ApplicationRadio = null
        + {static} final ADRESSE_VUE_RECEPTEUR : String = "/vues/Vue_Recepteur.fxml"
        - final directoryChooser : DirectoryChooser = new DirectoryChooser()
        - file : File
        - nbrMessage : int = 0
        + void setApplication(ApplicationRadio application)
        + BorderPane getBorderPaneRoot()
        - void clickedBtnEnregistrer(ActionEvent event)
        - void clickedBtnSelect(ActionEvent event)
        + String getEmplacementFichierSelect()
    }

    class ControleurVueMenu {
    	- darkNGreen RadioMenuItem
    	- blueNRed RadioMenuItem
        - vboxRoot : VBox
        - btnEmettre : Button
        - btnReception : Button
        - themeCourant : String = DARK_N_GREEN
        + {static} final DARK_N_GREEN : String = "/styles/DarkNGreen.css"
        + {static} final BLUE_N_RED : String = "/styles/BlueNRed.css"
        - application : ApplicationRadio = null
        + {static} final ADRESSE_VUE_MENU : String = "/vues/Vue_Menu.fxml"
        + void setApplication(ApplicationRadio application)
        + VBox getVboxRoot()
        - void clickedBtnEmettre(ActionEvent event)
        - void clickedBtnReception(ActionEvent event)
        - void selectedDarkNGreen(ActionEvent event)
        - void selectedBlueNRed(ActionEvent event)
        + String getThemeCourant()
    }
}

package "modeles" {
    class RepresentationBinaire {
        - octets : OctetBinaire[]
        - octetCourant : int
        + RepresentationBinaire(byte[] bytes)
        + RepresentationBinaire(OctetBinaire[])
        + OctetBinaire[] getOctets()
        + boolean hasNext()
        + OctetBinaire next()
        + Iterator<OctetBinaire> iterator()
        - {static} boolean validerOctets(byte[] octets)
        - {static} boolean validerOctets(OctetBinaire[] octets)
    }

    class OctetBinaire {
        - bits : byte[]
        - representationDecimale : byte
        - bitCourant : int
        + {static} {final} BITS_DANS_OCTET : byte
        + OctetBinaire(byte b)
        + OctetBinaire(byte[] bits)
        - void calculerBits(byte b)
        - byte[] decABin(byte b, byte[] representationBin, int index)
        + byte[] decABin(byte b)
        + byte[] getBits()
        + byte[] complementerADeux(byte[] bits)
        - void calculerRepresentationDecimal()
        + byte getOctetEnDecimal()
        + String toString()
        + boolean equals(Object obj)
        + Iterator<Byte> iterator()
        + boolean hasNext()
        + Byte next()
        - {static} boolean validerBits(byte[] bits)
        + {static} boolean validerBit(byte b)
    }
}

package "modeles.emetteur" {
    class GenerateurSon {
        - repr : RepresentationBinaire
        - donneesSon0 : byte[]
        - donneesSon1 : byte[]
        + GenerateurSon(RepresentationBinaire repr, float dureeEnSec)
        + void calculerSonsPourBits(float dureeEnSec)
        + byte[][] getDonneesSon()
        + {static} boolean validerRepresentation(RepresentationBinaire repr)
        + {static} boolean validerDureeEnSec(float duree)
    }

    class LecteurSon {
        - donneesSons : byte[][]
        - af : AudioFormat
        - sdl : SourceDataLine
        - dureeEnSec : float
        + LecteurSon(byte[][] donneesSons, float dureeEnSec)
        + void lireSons()
        - void creerAudioFormat()
        - void creerSourceDataLine()
        - void preparerDataLineAEnvoi()
        - void fermerDataLine()
        + {static} boolean validerDonneesSon(byte[][] donnees)
        + {static} boolean validerDuree(float duree)
    }
}

package "modeles.receveur" {
    class ReconstitueurDeMessages {
        - octetEnConstruction : byte[]
        - indiceConstructionCourant : int
        - octetsComplets : List<OctetBinaire>
        + ReconstitueurDeMessages()
        + void ajouterBit(byte bit)
        + RepresentationBinaire getRepresentationBinaire()
    }

    class EcouteurDeReception {
        - rdm : ReconstitueurDeMessages
        + EcouteurDeReception()
        + void ecouter()
        - Optional<Byte> analyserSignal()
    }
}

package "passerelle" {
    class PasserelleFichier{
        + {static} byte[] lireOctets(File fichier)
        + {static} void ecrireOctets(byte[] octets)
        + {static} void ecrireOctets(RepresentationBinaire binaire)
        + {static} File obtenirFichier(String chemin)
    }
}

package "tests" {
	class TestGenerateurSon {
		+ {static} void setUp()
		+ void testGenerateurSon()
		+ void testGenerateurSonInvalide()
		+ void testCalculerSonsPourBits()
		+ void testGetDonneesSon()
	}
	
	class TestLecteurSon {
		+ void testLecteurSon()
		+ void testLecteurSonInvalide()
		+ void testValiderDonneesSon()
		+ void testValiderDuree()
	}

    class TestOctetBinaire {
        ob : OctetBinaire
        + void testOctetBinaire()
        + void testOctetBinaireInvalide()
        + void testCalculerBits()
        + void testEquals()
        + void testToString()
    }

    class TestPasserelleFichier {
        + void testLireFichier()
    }

    class TestRepresentationBinaire {
        rb : RepresentationBinaire
        octets : byte[] = {0, 1, 2, 3};
        + void testRepresentationBinaire()
        + void testRepresentationBinaireInvalide()
        + void testGetOctets()
        + void testIterator()
    }

    class TestSuite {
    }
}

interface "Iterable<OctetBinaire>" as iterableOB {
    + OctetBinaire next()
    + boolean hasNext()
}
interface "Iterator<OctetBinaire>" as iteratorOB {
    + Iterator<OctetBinaire> iterator()
}
interface "Iterable<Byte>" as iterableBY {
    + Byte next()
    + boolean hasNext()
}
interface "Iterator<Byte>" as iteratorBY {
    + Iterator<Byte> iterator()
}

ApplicationRadio --> ControleurEnvoi
ControleurEnvoi --> PasserelleFichier
ControleurEnvoi --> RepresentationBinaire

OctetBinaire --|> iterableBY
OctetBinaire --|> iteratorBY


RepresentationBinaire --> OctetBinaire
RepresentationBinaire --|> iterableOB
RepresentationBinaire --|> iteratorOB

GenerateurSon --> RepresentationBinaire
GenerateurSon --> OctetBinaire

LecteurSon --> GenerateurSon

ControleurReception --> PasserelleFichier
ControleurReception --> EcouteurSignaux

EcouteurSignaux --> OctetBinaire
EcouteurSignaux --> Signal

Signal --> ValeurSignal

TestGenerateurSon --> GenerateurSon
TestLecteurSon --> LecteurSon

TestOctetBinaire --> OctetBinaire
TestPasserelleFichier --> PasserelleFichier
TestRepresentationBinaire --> RepresentationBinaire
@enduml